sudo: required
dist: trusty

# Caching so the next build will be fast too.
cache:
  directories:
    - ~/.stack
    - ~/.local
  apt: true

addons:
  apt:
    sources:
      - hvr-ghc
      - mono-nightly
    packages:
      - ghc-8.2.2
      - mono-devel
      - mono-utils

before_install:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
  - sudo apt-get update -qq
  - sudo apt-get install -qq dotnet-dev-1.0.0-preview2.1-003177
  # Add ghc to the PATH
  - export PATH=/opt/ghc/bin:$PATH
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - curl -L https://raw.githubusercontent.com/futurice/fum2github/3a270cf7a3b600900c1a8ed07c23d5f3ba8b115d/travis_long > travis_long && chmod +x travis_long

script:
  - ./travis_long stack +RTS -N2 -RTS --no-terminal --system-ghc --skip-ghc-check install idris
  - ./travis_long stack +RTS -N2 -RTS --no-terminal --system-ghc --skip-ghc-check test
