resolver: lts-11.14

packages:
  - location: .
  - location:
      git: https://github.com/bamboo/language-cil.git
      commit: 0438ed5173c9d0ddeb55f315464f5e9fec6c1731
    extra-dep: true
  - location:
      git: https://github.com/idris-lang/Idris-dev.git
      commit: 1510fce9236a088031f7468bf2024b31fe8d1165
    extra-dep: true
flags:
  idris:
    ffi: true
    gmp: true

extra-deps:
  - bool-extras-0.4.0
